### ISSUE TITLE
Problem making a simple fetch post

### ISSUE THREAD

**Issue by leocrawf** [NativeScript/nativescript-sdk-examples-ng#116]
Hello I have been playing around with nativescript. The biggest issue I am having is making http calls.

All the sample code works great except when I change the url I am having issues.

                import { Component, ChangeDetectionStrategy} from '@angular/core';

                @Component({
                selector: 'home',
                templateUrl: 'modules/home/home.component.html',
                styleUrls:['modules/home/home.component.css'],
                changeDetection: ChangeDetectionStrategy.OnPush
                })

                export class HomeComponent {
                register(){
                    fetch("http://myurl.com", {
                            method: 'post'
                        }).then(response => { 
                        
                            return response.json(); 

                        }).then(res => {
                            console.log("Response json:");
                            alert(JSON.stringify(res));                      
                        }).catch(err => {
                            console.log("Error occurred " + err.stack);
                        });
                }
              }

I am getting this error:

           V/GoogleSignatureVerifier(24051):    dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
            JS: Error occurred SyntaxError: Unexpected token N in JSON at position 0
            JS:     at parse (native)
            JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-na
            tivescript.js:190:28)
            JS:     at Object.onInvoke (/data/data/org.nativescript.StFrancis/files/app/tns_modules/@angular/core/bundles/core.umd.js:6206:41)
            JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-na
            tivescript.js:189:34)
            JS:     at Zone.run (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.
            js:83:43)
            JS:     at /data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:57
            JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zon
            e-nativescript.js:223:37)
            JS:     at Object.onInvokeTask (/data/data/org.nativescript.StFrancis/files/app/tns_modules/@angular/core/bundles/core.umd.js:6197:41
            )
            JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zon
            e-nativescript.js:222:42)
            JS:     at Zone.runTask (/data/data/org.nativescript.StFrancis/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescr
            ipt.js:123:47)

The interesting thing is that the rest api on the php page outputs this: 

{"file_id":"1","table_name":"site","table_id_column_name":"site_id","table_id_value":"1","file_type":"jpg","file_path":"59b355cd7880f51ac76559a2416a4a45.jpg","original_file_name":"MP900442493","created_by_user_id":"30","datetime_created":"2016-01-05 23:40:14"}

However If I should simply echo out the result with out running the rest api, like this:

     echo '{"file_id":"1","table_name":"site","table_id_column_name":"site_id","table_id_value":"1","file_type":"jpg","file_path":"59b355cd7880f51ac76559a2416a4a45.jpg","original_file_name":"MP900442493","created_by_user_id":"30","datetime_created":"2016-01-05 23:40:14"}';

I do not get an error if i do the above. What am I to understand from this? That because there is a delay in the rest api when it does its query the {n} http call return nothing before the result is generated, but if a static result is on the page already it works fine. Is there a way around this?

**Comment by tsonevn** [comment]
Hi @leocrawf,
Thank you for your interest in NativeScript,
I reviewed the case, however it could be related with the response of the rest API, you are using and the way you are converting the data to a JSON object. The given error could be caused if you try to `JSON.stringify(data)`, where the `data` is `undefined` object. Regarding to that you could also review, whether HTTP module methods: [getJSON ](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/http/http-get/http-get.ts#L43) or [getString](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/http/http-get/http-get.ts#L35) will work for you. Regarding to the topic, you should also know that by default the http requests for iOS has been forbidden. To be able to use HTTP request you could follow the instructions [here](http://stackoverflow.com/questions/30731785/how-do-i-load-an-http-url-with-app-transport-security-enabled-in-ios-9).

Regards,
@tsonevn

**Comment by leocrawf** [comment]
Thank you so much. Both HTTP module methods: getJSON or getString will worked. But now how would I loop through each item and add them to an array to bind them to some html.
the result would look something like this:
    {"file_id":"1","table_name":"site","table_id_column_name":"site_id","table_id_value":"1","file_type":"jpg","file_path":"59b355cd7880f51ac76559a2416a4a45.jpg","original_file_name":"MP900442493","created_by_user_id":"30","datetime_created":"2016-01-05 23:40:14"}

if I try :
       getJSON("http://url.com")
            .then((r) => {
                let rows = r;   
                 for (let item of rows) {
                        console.log(item); 
                 }
               
            }, (e) => {
                alert("GetJSON: " + e)
            });
i get : error TS2495: Type '{}' is not an array type or a string type.

**Comment by tsonevn** [comment]
Hi @leocrawf,
The given error has been caused due to the fact that you are using your JSON as array. You could review the sample code [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/http/http-get/http-get.ts#L43-L49), where has been shown how to access and bind the your JSON data. You could also review the sample code below:
_HTML_
```
<ScrollView>
    <StackLayout>
        <GridLayout rows="auto, auto">
            <Label row="0" text="origin" class="p-t-15 p-l-15 p-r-15" textWrap="true"></Label>
            <Label row="1" text="url" class="p-t-15 p-l-15 p-r-15" textWrap="true"></Label>
        </GridLayout>
    </StackLayout>
</ScrollView>
```
_Typescript_
```
export class HttpGetComponent implements OnInit {
    public firstProperty: string = "";
    public secondProperty: string = "";
    ngOnInit() {
    getJSON("https://httpbin.org/get")
            .then((r) => {
                this.firstProperty= (<any>r).table_name;
                this.secondProperty= (<any>r).table_id_column_name;
            }, (e) => {
                alert("GetJSON: " + e)
            });
   }
}
```

Hope this helps

**Comment by leocrawf** [comment]
I got this resolved!
