### ISSUE TITLE
Custom directive bug on android 7 real device 

### ISSUE THREAD

**Issue by realtebo** [NativeScript/nativescript-sdk-examples-ng#134]
![screenshot_2016-12-19-19-11-44-427_org nativescript nativescriptsdkexamplesng](https://cloud.githubusercontent.com/assets/1268699/21323790/5cd3d7a2-c61f-11e6-8b9a-96421c0b541d.png)

**Comment by NickIliev** [comment]
Hey @realtebo thank you for noticing this inconsistency. I;ve changed the Android version to be in Android green color. Fixed with this [PR](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/136)
