### ISSUE TITLE
Error in Typescript

### ISSUE THREAD

**Issue by arulonline** [NativeScript/nativescript-sdk-examples-ng#151]
Hi

i’m getting below error when i try to run native-script-sdk-examples-ng-master in ios emulator. Pls help me to resolve this error.

$ tns --version
2.4.2
$ tsc -version
Version 2.1.5
$ tns run ios
Executing before-prepare hook from /Users/xxxxx/Downloads/nativescript-sdk-examples-ng-master/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.1.5

49 declare var global: NodeJS.Global;
~

../node_modules/@types/node/index.d.ts(49,13): error TS2403: Subsequent variable declarations must have the same type. Variable 'global' must be of type 'any', but here has type 'Global'.

73 declare var require: NodeRequire;
~

../node_modules/@types/node/index.d.ts(73,13): error TS2403: Subsequent variable declarations must have the same type. Variable 'require' must be of type 'NativeScriptRequire', but here has type 'NodeRequire'.

85 declare var module: NodeModule;
~

../node_modules/@types/node/index.d.ts(85,13): error TS2403: Subsequent variable declarations must have the same type. Variable 'module' must be of type 'NativeScriptModule', but here has type 'NodeModule'.

3973 export = console;
~

../node_modules/@types/node/index.d.ts(3973,5): error TS2309: An export assignment cannot be used in a module with other exported elements.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....

**Comment by tsonevn** [comment]
Hi @arulonline 

This problem could be caused if you have installed `@type/node` package at the global level.
To check, whether this package exists on your machine, you could use `npm list -g @type/node` .

This package will lead to this error. You could try to remove it by using `npm uninstall -g @types/node` command, which should remove it.

To make sure that the command has removed all needed files you could open `/usr/local/lib/node_modules` folder and look for `@types` folder. If there is no such folder, then the command has removed everything successfully. 

If you still have the same problem, please build the app with `tns run ios --log trace` and send us the full log from the Terminal.

Hope this helps.
