### ISSUE TITLE
Closing modal dialog causes app to crash on older Android versions (API 17 or 19)

### ISSUE THREAD

**Issue by honrust** [NativeScript/nativescript-sdk-examples-ng#154]
I am facing an issue with the modal dialog. When closing the dialog (ie. calling ModalDialogParams.closeCallback() (see modal-view.ts l.29), the app crashes. This happens in the application that I am developing for a custumor, as well as in the sdk-examples app.
I have not found any workarounds or solutions so far.

**Comment by honrust** [comment]
See also https://github.com/NativeScript/NativeScript/issues/3547

**Comment by tsonevn** [comment]
duplicated with [#3547](https://github.com/NativeScript/NativeScript/issues/3547)
