### ISSUE TITLE
non angular version please.. 

### ISSUE THREAD

**Issue by narayananl23** [NativeScript/nativescript-sdk-examples-ng#161]
when can we expect -- Feature request

**Comment by tsonevn** [comment]
Hi @narayananl23,
We have plans to create such an app, which provides non-angular samples.
Unfortunately, I cannot commit to an exact time frame when this will be ready, but we will work on it for some of the next NativeScript releases.

**Comment by randy-johnson** [comment]
I was told in another comment that this would be worked on as soon as 2.5.0 was released.  Has that timeline been pushed back now?

**Comment by tsonevn** [comment]
Hi @randy-johnson ,
The timeline for this task been pushed back due to some major tasks. as I have mentioned we have plans to create such an app, unfortunately, I cannot commit to an exact time frame when this will be ready.

**Comment by randy-johnson** [comment]
Alrighty.  Understood.  Thank you for the clarification.
