### ISSUE TITLE
Please add SASS support with webpack

### ISSUE THREAD

**Issue by hiddencaliber** [NativeScript/nativescript-sdk-examples-ng#163]
I couldn't find any example that has NativeScript, Angular2, Webpack and SASS that works without error for  
AoT as well. Please provide one or point me to that project if you know.
Thanks.

**Comment by gund** [comment]
+1
I did `npm install -D nativescript-webpack-dev` and `tns install sass`, removed `app.css` adding instead `app.ios.sass` and `app.android.sass` files.
Then run my app via `npm run start-android-bundle` but got a few errors:

```
23:15-40 Critical dependency: the request of a dependency is an expression

ERROR in Entry module not found: Error: Can't resolve './app.css' in 'C:\Users\malke\Projects\SimpleReader\app'

ERROR in The loader "C:/Users/malke/Projects/SimpleReader/app/features/example/example.component.sass" didn't return a st
ring.

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\Users\malke\Projects\SimpleReader\app'
 @ ./main.aot.ts 4:29-62
```

Is there anywhere a complete setup with this stack?

**Comment by YvesCandel** [comment]
@gund I'm also looking around to have this work together with a solution using only SASS. Please let me know if you find an example somewhere!

**Comment by hypery2k** [comment]
you can take a look at our sample app with SASS-support: https://github.com/holisticon/nativescript-ngx-demo/tree/develop

**Comment by sis0k0** [comment]
One more sample app: 
https://github.com/sis0k0/nativescript-webpack-sass

If anyone have problems with webpack+sass, please open issue in the [`nativescript-dev-webpack`](https://github.com/nativescript/nativescript-dev-webpack) repo.

**Comment by ntrp** [comment]
For anybody stumbling on this:

The only necessary step is to move the mainSheet variable like this [webpack.config.js](https://github.com/sis0k0/nativescript-webpack-sass/blob/master/webpack.config.js#L11-L15).

**Comment by robinvanderknaap** [comment]
@ntrp's solution did not work for me. Here's a related issue, with a simple work-around in the comments from @mn_martin https://github.com/NativeScript/nativescript-dev-webpack/issues/178
