### ISSUE TITLE
Not able to run on iOS

### ISSUE THREAD

**Issue by PankajDuPont** [NativeScript/nativescript-sdk-examples-ng#164]
<img width="565" alt="screen shot 2017-03-08 at 9 16 12 pm" src="https://cloud.githubusercontent.com/assets/20765643/23710967/7efb8754-0444-11e7-9bad-1709c754eb8a.png">
 hanged here

**Comment by tsonevn** [comment]
Hi @PankajDuPont,
Could you provide some more info about your environment (CLI, node, CocoaPods versions)?
In the meantime, you could try to update your Cocoapods with `[sudo] gem install cocoapods` and to verify whether you will have the same behavior, while using `tns run ios` command.

Let me know, whether this helps.

**Comment by PankajDuPont** [comment]
Hi Nikolay,


Initially it did not work but now it is working for me.


Thanks & Regards,
Pankaj Gupta, Mobile Apps Specialist
Tata Consultancy Services
Contractor for DuPont AMS Mobility
Phone: +91-8800118671
Email: pankaj.gupta@dupont.com

________________________________
________________________________
