### ISSUE TITLE
while running ios an error occoured:Error: Command npm failed with exit code 243

### ISSUE THREAD

**Issue by 1243786870** [NativeScript/nativescript-sdk-examples-ng#166]
Copying template files...
  ◠ Installing tns-iosInstalling  tns-ios
  ◞ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◡ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◟ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◠ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◠ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◝ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◞ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◟ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◠ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠼ normalizeTree: sill install loadCur  ◡ Installing tns-ios⸨░░░░░░░░░░░░░░░░░░⸩ ⠧ normalizeTree: sill install loadCur  ◞ Installing tns-ios⸨   ░░░░░░░░░░░░░░░⸩ ⠴ cloneCurrentTree: sill cloneCurrent  ◡ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◟ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◜ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◠ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◝ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◞ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◡ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◟ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◜ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◠ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◝ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◞ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◡ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◟ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◜ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◠ Installing tns-ios⸨    ░░░░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: sill install loa  ◝ Installing tns-ios⸨       ░░░░░░░░░░░⸩ ⠴ loadRequestedDeps: verb afterAdd /U  ◞ Installing tns-ios⸨          ░░░░░░░░⸩ ⠙ diffTrees: sill install generateAct  ◟ Installing tns-ios⸨           ░░░░░░░⸩ ⠙ diffTrees: sill install generateActnativescript-sdk-examples-ng@0.1.0 /Users/yanghaitao/Desktop/nativescript-sdk-examples-ng
└── tns-ios@2.5.0 

Error: Command npm failed with exit code 243
# run ios

┌──────────────────────────────┬───────────────────────────────────────────┐
│ Usage                        │ Synopsis                                  │
│ Run on all connected devices │ $ tns run ios [--release] [--justlaunch]  │
│ Run on a selected connected  │ $ tns run ios [--device <Device ID>] [-   │
│ device                       │ -release] [--justlaunch]                  │
│ Start an emulator and run    │ $ tns run ios --emulator [<Emulator       │
│ the app inside it            │ Options>] [--release]                     │
└──────────────────────────────┴───────────────────────────────────────────┘

Runs your project on a connected iOS device or in the iOS Simulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console and watches for changes in your code. Once a change is detected, it synchronizes the change with all selected devices and restarts/refreshes the application.

IMPORTANT: Before building for iOS device, verify that you have configured a valid pair of certificate and provisioning profile on your OS X system. 

### Options

    * --no-watch - If set, changes in your code will not be reflected during the execution of this command.
    * --device - Specifies a connected device on which to run the app.
    * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate ios. You cannot use --device and --emulator simultaneously.
    * --release - If set, produces a release build. Otherwise, produces a debug build.
    * --justlaunch - If set, does not print the application output in the console.
    * --clean - If set, forces rebuilding the native application.

### Attributes

    * <Device ID> is the index or name of the target device as listed by $ tns device ios
    * <Emulator Options> is any valid combination of options as listed by $ tns help emulate ios

**Comment by tsonevn** [comment]
Hi @1243786870 
Thank you for your interest in NativeScript.
I reviewed your case, however, was unable to reproduce this behavior on my side.
Regard that, could you provide some more info about your environment (CLI versions, node). It would also help if you could give us info about the device or simulator, which you are using for testing.

Meanwhile, you could verify, whether you are using latest [LTS Node 6.10.0](https://nodejs.org/en/) and upgrade to it if it is needed.

**Comment by runbb** [comment]
problem update the nativescript waitout cli
like
```npm install nativescript@latest```
fix
```npm install -g nativescript@latest```

**Comment by maphybao** [comment]
@1243786870 你好，这个问题你解决了吗？我也碰到了这个现象，很头痛
