### ISSUE TITLE
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1

### ISSUE THREAD

**Issue by Bhushankumar-pawar** [NativeScript/nativescript-sdk-examples-ng#169]
I downloaded the project and try to run this project I am getting following errors:

**Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ cd /Users/bhushankumar/Downloads/nativescript-sdk-examples-ng-release ;
Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ tns run ios --emulator**

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: nativescript-angular@1.5.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.29, 0.0.30, 0.0.31, 0.0.32, 0.0.33, 0.0.34, 0.0.35, 0.0.36, 0.0.37, 0.0.38, 0.0.40, 0.0.41, 0.0.42, 0.0.43, 0.0.44, 0.0.45, 0.0.46, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.1-2016-07-18-737, 0.2.1-2016-07-21-752, 0.2.1-2016-07-25-760, 0.2.1-2016-07-26-765, 0.2.1-2016-07-27-772, 0.2.1-2016-07-28-778, 0.3.0-2016-08-01-779, 0.3.0-2016-08-01-781, 0.3.0-2016-08-02-785, 0.3.1-2016-08-04-787, 0.3.1-2016-08-08-788, 0.3.0, 0.4.0-beta1, 0.3.1, 0.4.0-2016-08-30-877, 0.4.0, 0.4.1-2016-08-31-879, 0.4.1-2016-09-08-882, 0.4.1-2016-09-09-888, 0.5.0-2016-09-09-897, 0.5.0-2016-09-09-898, 0.5.0, 0.5.1-2016-09-09-900, 0.6.0-2016-09-13-907, 0.6.1-2016-09-13-909, 0.6.0, 1.0.1-2016-09-15-918, 1.0.0-2016-09-15-916, 1.0.0, 1.0.1-2016-09-16-920, 1.0.1-2016-09-27-923, 1.0.2-2016-09-27-925, 1.0.1, 1.0.2-2016-09-30-928, 1.0.2-2016-10-10-932, 1.0.2-2016-10-13-936, 1.0.2, 1.1.0-2016-10-13-940, 1.1.0, 1.1.0-2016-10-13-942, 1.1.0-2016-10-21-950, 1.1.1-2016-10-21-951, 1.1.2-2016-10-21-953, 1.1.1, 1.1.2-2016-10-21-955, 1.1.2-2016-10-25-958, 1.1.2-2016-10-28-984, 1.1.2-2016-10-28-986, 1.1.3-2016-10-28-988, 1.1.2, 1.1.3-2016-10-31-994, 1.1.3-2016-11-03-997, 1.2.0-2016-11-08-998, 1.2.0-2016-11-14-1009, 1.2.0-2016-11-16-1016, 1.1.3, 1.2.0-2016-11-18-1030, 1.2.0-2016-11-19-1033, 1.2.0-2016-11-19-1040, 1.2.0-2016-11-22-1053, 1.2.0-2016-11-23-1057, 1.2.0-2016-11-24-1066, 1.2.0-2016-11-24-1067, 1.2.0-2016-11-25-1073, 1.2.0-2016-11-25-1078, 1.2.0-2016-11-25-1085, 1.3.0-2016-11-28-1093, 1.3.0-2016-11-29-1105, 1.3.0-2016-11-29-1108, 1.3.0-2016-11-30-1112, 1.2.0, 1.3.0-2016-12-06-1124, 1.3.0-2016-12-07-1129, 1.3.0-2016-12-08-1145, 1.3.0-2016-12-08-1148, 1.3.0-2016-12-09-1152, 1.3.0-2016-12-09-1155, 1.3.0-2016-12-13-1161, 1.3.0-2016-12-13-1164, 1.3.0-2016-12-15-1167, 1.3.0-2017-01-04-1179, 1.3.1-2017-01-04-1182, 1.3.1-2017-01-05-1183, 1.3.0, 1.3.1-2017-01-13-1198, 1.4.1-2017-01-13-1201, 1.4.1-2017-01-16-1206, 1.4.1-2017-01-23-1222, 1.4.1-2017-01-26-1223, 1.4.1-2017-01-30-1226, 1.4.1-2017-01-31-1230, 1.4.0, 1.4.1-2017-02-08-1239, 1.4.1-2017-02-23-1261, 1.4.1-2017-02-27-1264, 1.4.1, 1.4.2-2017-02-27-1267, 1.4.2-2017-03-08-1284, 1.4.2-2017-03-13-1311, 1.4.2-2017-03-13-1316, 1.4.2-2017-03-13-1315, 1.4.2-2017-03-14-1323, 1.4.2-2017-03-16-1329, 1.4.2-2017-03-21-1351
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'nativescript-sdk-examples-ng'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bhushankumar/Downloads/nativescript-sdk-examples-ng-release/npm-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1
Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ 
Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ 
Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ 
Bhushankumars-MacBook-Pro-2:nativescript-sdk-examples-ng-release bhushankumar$ tns run ios --emulator
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: nativescript-angular@1.5.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.29, 0.0.30, 0.0.31, 0.0.32, 0.0.33, 0.0.34, 0.0.35, 0.0.36, 0.0.37, 0.0.38, 0.0.40, 0.0.41, 0.0.42, 0.0.43, 0.0.44, 0.0.45, 0.0.46, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.1-2016-07-18-737, 0.2.1-2016-07-21-752, 0.2.1-2016-07-25-760, 0.2.1-2016-07-26-765, 0.2.1-2016-07-27-772, 0.2.1-2016-07-28-778, 0.3.0-2016-08-01-779, 0.3.0-2016-08-01-781, 0.3.0-2016-08-02-785, 0.3.1-2016-08-04-787, 0.3.1-2016-08-08-788, 0.3.0, 0.4.0-beta1, 0.3.1, 0.4.0-2016-08-30-877, 0.4.0, 0.4.1-2016-08-31-879, 0.4.1-2016-09-08-882, 0.4.1-2016-09-09-888, 0.5.0-2016-09-09-897, 0.5.0-2016-09-09-898, 0.5.0, 0.5.1-2016-09-09-900, 0.6.0-2016-09-13-907, 0.6.1-2016-09-13-909, 0.6.0, 1.0.1-2016-09-15-918, 1.0.0-2016-09-15-916, 1.0.0, 1.0.1-2016-09-16-920, 1.0.1-2016-09-27-923, 1.0.2-2016-09-27-925, 1.0.1, 1.0.2-2016-09-30-928, 1.0.2-2016-10-10-932, 1.0.2-2016-10-13-936, 1.0.2, 1.1.0-2016-10-13-940, 1.1.0, 1.1.0-2016-10-13-942, 1.1.0-2016-10-21-950, 1.1.1-2016-10-21-951, 1.1.2-2016-10-21-953, 1.1.1, 1.1.2-2016-10-21-955, 1.1.2-2016-10-25-958, 1.1.2-2016-10-28-984, 1.1.2-2016-10-28-986, 1.1.3-2016-10-28-988, 1.1.2, 1.1.3-2016-10-31-994, 1.1.3-2016-11-03-997, 1.2.0-2016-11-08-998, 1.2.0-2016-11-14-1009, 1.2.0-2016-11-16-1016, 1.1.3, 1.2.0-2016-11-18-1030, 1.2.0-2016-11-19-1033, 1.2.0-2016-11-19-1040, 1.2.0-2016-11-22-1053, 1.2.0-2016-11-23-1057, 1.2.0-2016-11-24-1066, 1.2.0-2016-11-24-1067, 1.2.0-2016-11-25-1073, 1.2.0-2016-11-25-1078, 1.2.0-2016-11-25-1085, 1.3.0-2016-11-28-1093, 1.3.0-2016-11-29-1105, 1.3.0-2016-11-29-1108, 1.3.0-2016-11-30-1112, 1.2.0, 1.3.0-2016-12-06-1124, 1.3.0-2016-12-07-1129, 1.3.0-2016-12-08-1145, 1.3.0-2016-12-08-1148, 1.3.0-2016-12-09-1152, 1.3.0-2016-12-09-1155, 1.3.0-2016-12-13-1161, 1.3.0-2016-12-13-1164, 1.3.0-2016-12-15-1167, 1.3.0-2017-01-04-1179, 1.3.1-2017-01-04-1182, 1.3.1-2017-01-05-1183, 1.3.0, 1.3.1-2017-01-13-1198, 1.4.1-2017-01-13-1201, 1.4.1-2017-01-16-1206, 1.4.1-2017-01-23-1222, 1.4.1-2017-01-26-1223, 1.4.1-2017-01-30-1226, 1.4.1-2017-01-31-1230, 1.4.0, 1.4.1-2017-02-08-1239, 1.4.1-2017-02-23-1261, 1.4.1-2017-02-27-1264, 1.4.1, 1.4.2-2017-02-27-1267, 1.4.2-2017-03-08-1284, 1.4.2-2017-03-13-1311, 1.4.2-2017-03-13-1316, 1.4.2-2017-03-13-1315, 1.4.2-2017-03-14-1323, 1.4.2-2017-03-16-1329, 1.4.2-2017-03-21-1351
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'nativescript-sdk-examples-ng'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bhushankumar/Downloads/nativescript-sdk-examples-ng-release/npm-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1

**Comment by sis0k0** [comment]
Should be fixed with #170 now.

**Comment by Bhushankumar-pawar** [comment]
Thanks. It works.
