### ISSUE TITLE
Issue in use scrollView in tabView 

### ISSUE THREAD

**Issue by gauravbabu74** [NativeScript/nativescript-sdk-examples-ng#176]
Please check and give me some best way to solve this problem. I am using tabView and after multiple 
 gridview under scroll view. Before giving any answer me please check at your end.

Only one content is showing on device under scrollView. Please check and confirm me as issue will resolve.

**Comment by tsonevn** [comment]
Hi @gauravbabu74,
I tested your case on my side, however, was unable to reproduce this scenario.
For your help, I am attaching sample project, which you could review and make the needed changes.
It would also help if you could provide some more info about your environment(CLI, node versions). 
[Archive.zip](https://github.com/NativeScript/nativescript-sdk-examples-ng/files/1007614/Archive.zip)
