### ISSUE TITLE
Webpack bundling issue

### ISSUE THREAD

**Issue by dennis-montana** [NativeScript/nativescript-sdk-examples-ng#178]
When running `npm run build-android-bundle` we get the following error:

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in /Users/dennis/Desktop/nativescript-sdk-examples-ng/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/dennis/Desktop/nativescript-sdk-examples-ng/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts, resolving symbol ɵf in /Users/dennis/Desktop/nativescript-sdk-examples-ng/node_modules/nativescript-angular/node_modules/@angular/core/core.d.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/dennis/Desktop/nativescript-sdk-examples-ng/app'
 @ ./main.aot.ts 2:0-60

**Comment by avinashsindhu** [comment]
same issue i am also facing  when i am running npm run build-android-bundle
with a  reference project https://github.com/TeamMaestro/angular-native-seed , i build my own project  but in my reference project i am able running the above cmd and  getting  the build ,here in my project i am getting error as shown below 

ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported.
Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in native -seed-app/node_modules/@angular/core/core.d.ts, resolving symbol ɵe in native-seed-app/node_modules/@angular/core/core.d.
ts, resolving symbol ɵe in app/node_modules/@angular/core/core.d.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' 
 @ ./main.aot.ts

**Comment by avinashsindhu** [comment]
Ng --version 
@angular/cli: 1.0.0
node: 6.11.2
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/compiler-cli: 4.1.3
@ngtools/webpack: 1.5.6
from my nativescript
