### ISSUE TITLE
How to use *ngFor inside a custom directive ? Anything to import while using *ngFor ?

### ISSUE THREAD

**Issue by sagarpandya94** [NativeScript/nativescript-sdk-examples-ng#182]
I am using *ngFor with StackLayout inside a custom directive like: 

<custom-directive>
<StackLayout *ngFor="let item of projectList">
            <Label [text]="item.name"></Label>
</StackLayout>
</custom-directive>

And I am getting this error:
Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations".

I get the same error if i try to use *ngIf.

I have added the component in module file as well. I think I am missing something to import somewhere, not sure what it is.
Any help is appreciated.

Thank you.

**Comment by dinesh36** [comment]
I found an document https://docs.nativescript.org/angular/code-samples/ui/ng-directives.html for the using of *ngFor , but when I try to use that , I got template parsing error.

**Comment by tsonevn** [comment]
Hi @sagarpandya94, 
Excuse us for the delay in reply, however, could you provide some more info about your case and what do you expect as a final result?
It would also help if you could also provide some code sample, which could be used for debugging.

**Comment by wanpeng2008** [comment]
The same issue, after i cancel the imports of "NativeScriptModule" from non-AppModule.
It's solved after i reimport the @angular/common
