### ISSUE TITLE
[Feature request] Add return Press event for the TextView component.

### ISSUE THREAD

**Issue by bachras** [NativeScript/nativescript-sdk-examples-ng#183]
Hi,

I am trying to implement TexView and submit it by pressing return button. However instead of submitting cursor goes to new line and doesn't do anything else. I have tried all examples i could found online, i also install this examples app and noticed that it is the same behaviour.

I added alert() :
````
submit(args) {
        alert("Submit Text: " + this.tvtext);
        let textview: TextView = <TextView>args.object;
        if (isAndroid) {
            textview.android.clearFocus();
        }
    }
`````
But nothing is alerted after return(Send) button is clicked. Does anyone have idea what could be wrong? Thank you in advance.

**Comment by tsonevn** [comment]
Hi @bachras,
This is something expected while pressing the return button for the `TextView`. This component does not have exposed `returnPressEvent` as you can see in the documentation [here](http://docs.nativescript.org/api-reference/classes/_ui_text_view_.textview.html).
Instead of using `TextView` you could use `TextField`, where this event is available. For example:
HTML
```
<GridLayout rows="" columns="">
    <TextField hint="Enter text" text="" returnKeyType="done" (returnPress)="submit()"></TextField>
    
</GridLayout>
```
TypeScript
```
submit(){
        console.log("on submit tap ");
    }
```

**Comment by sitefinitysteve** [comment]
Can we not make this a FR to ADD that event to TextView?

**Comment by bradmartin** [comment]
I don't think it actually works with Angular @sitefinitysteve - just tried, no go. Was running into this myself. Gonna switch to a textfield and call it a day 👍

**Comment by hairen** [comment]
@tsonevn Why was this issue closed? It would be great to have `returnPressEvent` in **TextView**!

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#4882
