### ISSUE TITLE
own dialog

### ISSUE THREAD

**Issue by radhakrishnan0404** [NativeScript/nativescript-sdk-examples-ng#207]
how to create our own dialog box without ok or submit button in nativescript @jbristowe

**Comment by tsonevn** [comment]
Hi @radhakrishnan0404,
One possible way for your case is to create your own modal page, where you could modify the UI as you needs. The appropriate example could be found [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page).
