### ISSUE TITLE
barcode scanner

### ISSUE THREAD

**Issue by radhakrishnan0404** [NativeScript/nativescript-sdk-examples-ng#210]
an issue has been detected i created a sidedrawer template  by using 

tns create my-project-name --template nativescript-angular-drawer-template

and i added a simple scan button in home page and added bar code scanner plugin all worked fine

on clicking scan button for barcodescanner it goes to camera after scanning qr code it is coming to its same page that is where i have kept simple scan button. In the same page i have kept label 
<StackLayout columns="*, auto"> 
            <label  text="{{products.id}}"></label>
            <label  text="{{products.name}}"></label>
            <label  text="{{products.price}}"></label>
        </StackLayout>
it is not fetching the data to label but while creating simple app it works fine in drawer template only its not working how to get rid of it

**Comment by tsonevn** [comment]
Hi @radhakrishnan0404,
First of all thank you for your interest in NativeScript,
Could you provide some more info about the problem you are facing? it would help if you could provide the specific error, which is thrown and sample project, which could be debugged locally.

Bear in mind that the above-mentioned template is not officially supported by the NativeScript team and if there is an issue related to it, you could report them to its [repository](https://github.com/shripalsoni04/nativescript-angular-drawer-template).
