### ISSUE TITLE
how to update user information 

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-sdk-examples-ng#214]
am building a social app with angular and am looking for a way to make users update their infromations from their profile 
need help ASAP
thanks

**Comment by tsonevn** [comment]
Hi @nelsonwilliam11,
Could you provide more info about your case and what you are trying to achieve?

**Comment by nelsonwilliam11** [comment]
hi @tsonevn thanks for your reply 
what am trying to achieve is to make users insert their user names, location, and occupation so when someone visit their profile should be able to see their user name location etc.
for example Facebook user profile page i want something similar

**Comment by tsonevn** [comment]
HI @nelsonwilliam11,
Excuse us for the delay in reply,
For your case, you could review the [dataentry-signup](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/common-screens-category/dataentry/dataentry-signup). About the getting the location, you could use the [nativescript-geolocation](https://www.npmjs.com/package/nativescript-geolocation), which provides this functionality.

For further questions, please use our NativeScritp [forum](https://discourse.nativescript.org/).
