### ISSUE TITLE
webview canGoBack event is not working android & ios

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/nativescript-sdk-examples-ng#241]
How to handle the **webview.CanGoBack() & goback()** event in webview .
if (webview.canGoBack) { webview.goBack(); }

Please suggest on this event..

**Comment by NickIliev** [comment]
@priyangamani [this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/d52bf8710d7e9f8c5f20532bc73f7e3423526019/app/ui-category/web-view/basic-web-view/basic-web-view.component.ts#L40-L42) demonstrates how to use the property `canGoBack` and the method `goBack()`

Steps - open the WebView example and navigate inside the sample web site (www.nativescript.org).
Once a navigation is done you can press the back button to navigate back.

**Comment by priyangamani** [comment]
Thanks for your reply.I tried to use navigation back button but  webview.canGoBack  property will not fire . How do I detect when a WebView page is trying to close?

**Comment by NickIliev** [comment]
@priyangamani 
Try using the `unloaded` event for your WebView.
