### ISSUE TITLE
Error occurred while tns run

### ISSUE THREAD

**Issue by LHLK** [NativeScript/nativescript-sdk-examples-ng#246]
Try to run the package with the following error.  tns version 3.3.1. on Win 10. Angular  5.0.1
Error details:
Running full build
finished with reading lines with js files
Error: Failed to crunch file E:\Project\Training\NativeScript\Tutorial\theme-master\test\nativescript-sdk-examples-ng\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.4.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into E:\Project\Training\NativeScript\Tutorial\theme-master\test\nativescript-sdk-examples-ng\platforms\android\build\intermediates\res\merged\F0F1F2\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mergeF0F1F2DebugResources'.
> Error: Failed to crunch file E:\Project\Training\NativeScript\Tutorial\theme-master\test\nativescript-sdk-examples-ng\platforms\android\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\11.4.0\res\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png into E:\Project\Training\NativeScript\Tutorial\theme-master\test\nativescript-sdk-examples-ng\platforms\android\build\intermediates\res\merged\F0F1F2\debug\drawable-xxhdpi-v4\common_google_signin_btn_icon_light_normal_background.9.png

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Unable to apply changes on device: emulator-5554. Error is: Command gradlew.bat failed with exit code 1.

Regards,
LH

**Comment by tsonevn** [comment]
Hi @LHLK,

Regarding the provided log from the console, I found that this error appears when the max file path line of the operating system is reached. For a solution, you could review [this ](https://stackoverflow.com/a/41314222/6133327) thread in StackOverflow.

 If the problem persists please provide info about the exact steps, which you are using? Also, you could build the project with `tns run android --log trace` and to send us the full log from the console.

**Comment by LHLK** [comment]
Hi tsonevn,
Thanks for your prompt reply.  It works now. FYI, same error came out while I try to create a new project without using the --template flag e.g. tns create HelloWorldNoTemplate --ng.  However, if I followed your tutorial using the tns create HelloWorld --template nativescript-template-ng-tutorial.  No errors found.
