### ISSUE TITLE
Errors during installation 

### ISSUE THREAD

**Issue by LHLK** [NativeScript/nativescript-sdk-examples-ng#247]
Followed the below instructions:
git clone --depth 1 https://github.com/NativeScript/nativescript-sdk-examples-ng.git
cd nativescript-sdk-examples-ng
tns run android

Errors:  
user@LAPTOP-1MS538L2 MINGW64 /e/allsamples/nativescript-sdk-examples-ng (master)
$ tns platform add android
Copying template files...
Installing  tns-android
  / Installing tns-android+ tns-android@4.0.0-2017-12-19-05
added 22 packages, removed 23 packages and updated 397 packages in 48.323s
cp: no such file or directory: E:\allsamples\nativescript-sdk-examples-ng\node_modules\tns-android\framework\libs
# platform add

┌────────────────────────

Please help.
Regards,
LH

**Comment by NickIliev** [comment]
@LHLK can you pen the `package.json` and see if there is a `tns-android` listed as a **dependency**.
if so - remove the entry and rebuild the project.

**Comment by LHLK** [comment]
Hi NickIliev, great support as usual and it's working now.  BTW, in light of ease, could you point me to some resources regarding the css gradient (reference to : https://github.com/NativeScript/NativeScript/issues/539).  My client would like to have the Android button native gradient look like this: https://www.dibbus.com/2011/02/gradient-buttons-for-android/

Great support again & Many Thanks!
LH

**Comment by NickIliev** [comment]
@LHLK gradient support is logged as a feature [here](https://github.com/NativeScript/NativeScript/issues/539) (there are some possible solutions provided in the linked issue). Another possibility is to use [nativescript-gradient plugin.](https://www.npmjs.com/package/nativescript-gradient)

**Comment by x00** [comment]
removing it as dependency doen't work for me I get the same error.

**Comment by x00** [comment]
keeps on on referring to 
`node_modules/tns-android/framework/libs`
