### ISSUE TITLE
Error : Flavor nativescript-camera has unknown dimension nativescript-camera

### ISSUE THREAD

**Issue by nachiketglobant** [NativeScript/nativescript-sdk-examples-ng#273]
![image](https://user-images.githubusercontent.com/18402874/38351636-0472822a-38ce-11e8-99b4-c7f2f08fce30.png)

Error : Flavor nativescript-camera has unknown dimension nativescript-camera

I get the above error after I execute 'tns run android'
Can you please help ?

**Comment by NickIliev** [comment]
@nachiketglobant I am not able to reproduce the issue on my side.
Can you please remove the `node_modules` and `platforms` folders and rebuild the project.
If the issue persists please post the versions of NativeScript CLI(`tns-version`) and if there are any changes made in the `package.json`

**Comment by NickIliev** [comment]
@nachiketglobant what is the version of your NativeScript CLI (`tns --version`)

**Comment by shanncute** [comment]
Hi @nachiketglobant 

Did you found the solution for this issue? Im facing the same issue. pls suggest me to fix this issue.
