### ISSUE TITLE
Tabview display problem

### ISSUE THREAD

**Issue by liuchuancong** [NativeScript/nativescript-sdk-examples-ng#293]
when i  use TabView in my code, if 
```
<TabView (selectedIndexChanged)="onSelectedIndexChanged($event)" selectedIndex="{{selIndex}}"  androidTabsPosition="bottom">
    <StackLayout *tabItem="{title: 'Toaday', iconSource: 'res://icon_toaday'}">
        <Toaday></Toaday>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Time', iconSource: 'res://icon_time'}">
        <Time></Time>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Koran', iconSource: 'res://icon_koran'}">
        <koranhome [aIndex]="selectIndex"></koranhome>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Kaaba', iconSource: 'res://icon_kaaba'}">
        <Kaaba  [kIndex]="selectIndex"></Kaaba>
    </StackLayout>

    <StackLayout *tabItem="{title: 'Mine', iconSource: 'res://icon_mine'}">
        <Mine></Mine>
    </StackLayout>
</TabView>
```
StackLayout > 5
There was an error

![2018-07-01 11-01-24](https://user-images.githubusercontent.com/36957912/42130681-4062dc28-7d1e-11e8-960e-289f33b56df3.png)
Screen Resolution 720p
in 1080p it works!

**Comment by tsonevn** [comment]
Hi @liuchuancong,
Can you provide more info about the issue, you are facing and about the platform, you are using (iOS/ Android)? 
Bear in mind if you set up more then five tabs on some Android device the Tabs cannot be scaled on the device screen. In this case, the Tabs will be displayed on scrollable View. You will still be able to access all tabs by using the scroll. Review the attached GIF file.
![screencast 2018-07-04 at 12 47 38 pm](https://user-images.githubusercontent.com/17448734/42270381-610ebdee-7f89-11e8-82e8-f22b87f09e43.gif)
