### ISSUE TITLE
NativeScript samples site is down

### ISSUE THREAD

**Issue by starquake** [NativeScript/nativescript-sdk-examples-ng#296]
When I follow the link to http://docs.nativescript.org/angular/code-samples/overview.html it says 404,

**Comment by bradrice** [comment]
I think they have changed up paths. I was going to put in an issue, too.

Try: https://market.nativescript.org/?tab=samples&framework=angular&category=all_samples

**Comment by tsonevn** [comment]
Hi all, 
The broken links in the ReadMe file are already fixed. The https://docs.nativescript.org/angular/ui/components is the link, which should replace the overview.
