### ISSUE TITLE
Broken anchor link

### ISSUE THREAD

**Issue by shiv19** [NativeScript/nativescript-sdk-examples-ng#316]
https://docs.nativescript.org/angular/ui/ng-ui-widgets/action-bar#setting-the-title-text

In this page, `#setting-the-title-text` does not exist.
But it is being used in the `iOS Specifics` tip under the `Navigation Button` section.

**Comment by NickIliev** [comment]
Fixed via [https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/318](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/318)
