### ISSUE TITLE
Replace the link to `androiddrawables.com`

### ISSUE THREAD

**Issue by shiv19** [NativeScript/nativescript-sdk-examples-ng#317]
In this link: https://docs.nativescript.org/angular/ui/ng-ui-widgets/action-bar#android

http://androiddrawables.com no longer exists.
I have attempted to recover it using wayback machine.

you can point it to `https://shiv19.com/assets/Android%20Drawables.htm`

**Comment by NickIliev** [comment]
@shiv19 thanks for reporting and for the generated archived link. Still, I've replaced the link with the official list of Android draw3ables just to be up-to-date. [PR here](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/318)
