### ISSUE TITLE
error TS2304: Cannot find name 'ObservableArray'.

### ISSUE THREAD

**Issue by marklanhamhc** [NativeScript/nativescript-sdk-examples-ng#324]
Just been trying to setup the search functionality defined on this tutorial page however once I get the code in I keep getting the error message: `error TS2304: Cannot find name 'ObservableArray'.`
https://docs.nativescript.org/angular/ui/ng-ui-widgets/search-bar

**Comment by tsonevn** [comment]
Hi @marklanhamhc,
Make sure that you have import the `ObservableArray` module as it is shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/ng-ui-widgets-category/search-bar/clear-search-bar/clear-search-bar.component.ts#L5).

**Comment by marklanhamhc** [comment]
Ok great, thanks!
