### ISSUE TITLE
Readme.md includes wrong URL

### ISSUE THREAD

**Issue by carlosrubio** [NativeScript/nativescript-sdk-examples-ng#33]
https://github.com/NativeScript/nativescript-sdk-examples-preview/blob/master/sdk-examples.md returns a 404.

[At line 95](https://github.com/NativeScript/nativescript-sdk-examples-ng/blame/master/README.md#L95)

**Comment by zh-m** [comment]
Hi Carlos, 

We modified the README.md and CONTRIBUTE.md files and the link you are referring to is also fixed to be the correct one (i.e. https://github.com/NativeScript/nativescript-sdk-examples-ng-preview).
