### ISSUE TITLE
Search Bar keyboard popup issue on Android

### ISSUE THREAD

**Issue by marklanhamhc** [NativeScript/nativescript-sdk-examples-ng#337]
I've noticed an issue with the keyboard popping up when using the TabView on Android. It seems to happen on pages either side of the Search page and its the same issue as mentioned in this post: https://github.com/NativeScript/NativeScript/issues/6160. This is a Nativescript Angular project though.

**Comment by tsonevn** [comment]
Hi @marklanhamhc,
Thank you for cantacting us.

I would suggest keeping the conversation on an issue https://github.com/NativeScript/NativeScript/issues/6160 . You can add your comment on it if you would like to provide some additional info. Also, you can check the provided solution - https://github.com/NativeScript/NativeScript/issues/6160#issuecomment-412778200.
