### ISSUE TITLE
http DI example not using root injector

### ISSUE THREAD

**Issue by yringler** [NativeScript/nativescript-sdk-examples-ng#357]
Several times at https://docs.nativescript.org/angular/ng-framework-modules/http, it is made clear that
> Note that the services should be explicitly declared in providers

There are [other ways to do DI in angular](https://angular.io/guide/hierarchical-dependency-injection#where-to-configure-providers), notably 
```typescript
@Injectable({
  providedIn: 'root',
})
export class MyAwesomeDataService{
  // Service code...
}
```
or specifying an NgModule in the provided in option.

Are these also ok?
If they are ok, the documentation should be less "opinionated" in tone, and if it's not ok (or just not reccomended) the docs should say why.

**Comment by NickIliev** [comment]
@yringler you are absolutely right - using `provideIn` is another way to declare your service provider. In fact, we are using this approach in our templates (e.g. [here](https://github.com/NativeScript/template-hello-world-ng/blob/master/src/app/item/item.service.ts#L6)).
