### ISSUE TITLE
application settings gives undefined in other component

### ISSUE THREAD

**Issue by gsarme** [NativeScript/nativescript-sdk-examples-ng#371]
I want to store some information in application settings after login. When I change component if I use getString(key) it gives undefined

**Comment by tsonevn** [comment]
Hi @gsarme,
Can you send us a sample project, which can be used for reproducing the issue, you are facing?

**Comment by gsarme** [comment]
Hi @tsonevn,
sorry but I decide to use a different approach. Instead of using application-settings I used localstorage.
Thanks anyway

**Comment by tsonevn** [comment]
HI @gsarme,
I am still unable to recreate an issue with the application-settings module. For your convenience,  I am attaching my sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-sdk-examples-ng/files/3094064/Archive.zip)


In my opinion, we can close this issue for now. I will reopen it when we have a sample project, where the problem can be recreated.
