### ISSUE TITLE
The Date Picker example needs context

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-sdk-examples-ng#42]
See http://docs.nativescript.org/angular/sdk-examples/date-picker.html#configure-date-picker.

`datePicker` is never explained, so this example isn’t copy and pasteable. I’d love to see a markup example first, and then maybe a code example that explains this context.

**Comment by tjvantoll** [comment]
The same is true of TimePicker (http://docs.nativescript.org/angular/sdk-examples/time-picker.html), so I added that to this issue as well.

**Comment by tsonevn** [comment]
Hi @tjvantoll,
Thank you for reporting this problem with  those articles.
I made some changes with the code snippets that have been used when the articles are generating.
Pull request: [#46](https://github.com/NativeScript/nativescript-sdk-examples-ng/pull/46)

**Comment by tjvantoll** [comment]
Looks great. Thanks @tsonevn!
