### ISSUE TITLE
Please keep core cookbook module examples

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-sdk-examples-ng#51]
@tjvantoll Has asked me to drop a line here reminding us to keep the core cookbook module docs for example, `image-source`, `file-system`, etc.

**Comment by tjvantoll** [comment]
Indeed. Also `http`, etc. I’m glad we started with UI examples, but I think we need to make getting these utilities in the starters to make this as useful as the existing cookbook.

**Comment by NickIliev** [comment]
Core cookbook examples added for modules

**DONE**
- application
- application-settings
- color
- connectivity
- fetch
- file-system
- formatted-string
- fps-meter
- http
- location
- platform
- timer
- trace

**In Progress**
 - nativescript-camera

**Comment by valentinstoychev** [comment]
@NickIliev - are these available in the docs already?

**Comment by NickIliev** [comment]
@valentinstoychev yep = all of them are placed n "Code Samples" section of the Angular part of the documentation.

lastest **DONE**

- nativescript-camera
- flexbox layout examples
- common content screens
