### ISSUE TITLE
Range slider

### ISSUE THREAD

**Issue by genesis06** [NativeScript/nativescript-sdk-examples-ng#58]
Hi,

Is there a way of making a range slider? Please, if somebody knows something, I would be so thanksful.

Kind regards

**Comment by tsonevn** [comment]
Hi @genesis06,
Thank you for your interest in NativeScript.

At the moment our Slider component do not support such a functionality. In regard to that you could log new feature request in [this ](https://github.com/NativeScript/NativeScript) repo, where you could describe the needed feature. There you would be able to track its status and other users could vote for the feature's implementation.


Regards,
@tsonevn
