### ISSUE TITLE
Horrible performance on real Android device

### ISSUE THREAD

**Issue by fleuverouge** [NativeScript/nativescript-sdk-examples-ng#71]
Hi,
I've run the app in Android & iOS emulators & real devices. Everything is fine except for the Android phone. The app is slow, sometimes unresponsive in every screen. The sample apps in Play Store run well (not as smoothly as in iOS though). 

Here's the device info:
* Model: Samsung Galaxy J Docomo SC-02F
* RAM: 3GB
* Chipset: Qualcomm MSM8974 Snapdragon 800
* OS version: 4.4.2

I can't get any other Android device so I'm not sure if this problem is caused by the device or the code. 

I wonder if there's any special configuration and/or command required to build the app? (I simply run `tns run android`)

**Comment by tsonevn** [comment]
Hi @fleuverouge,
Could you provide more info about the examples that are not responsive or you have found problem. This is a known issue with slow navigation in Android, while usuing `tns-core-modules` 2.3.0 . However we upgrade the `app` to use `@next` modules, where this issue has been fixed. 
Regards,
@tsonevn
